services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/issue_tracker
      SPRING_DATASOURCE_PASSWORD: postgres
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: issue_tracker
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
