spring:
  application:
    name: issue-tracker
  datasource:
    url: jdbc:postgresql://localhost/issue_tracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
